/* global mermaid, acquireVsCodeApi */
(function () {
  const vscode = acquireVsCodeApi();
  const tabs = document.getElementById('tabs');
  const content = document.getElementById('content');
  const status = document.getElementById('status');

  const dark = document.body.classList.contains('vscode-dark') ||
    document.body.classList.contains('vscode-high-contrast');
  // suppressErrorRendering: a broken diagram must throw (we render our own
  // fallback) instead of mermaid injecting an error banner into <body>.
  mermaid.initialize({
    startOnLoad: false,
    theme: dark ? 'dark' : 'default',
    securityLevel: 'strict',
    suppressErrorRendering: true,
  });

  const LOC_RE = /\[([\w@./\\-]+\.[\w]+):(\d+)\]/g;

  function esc(s) {
    return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  }

  // Turn "[path/file.ts:42]" occurrences into clickable links (for HTML text).
  function linkify(s) {
    return esc(s).replace(LOC_RE, (m, file, line) =>
      `<a class="loc" data-file="${file}" data-line="${line}">[${file}:${line}]</a>`);
  }

  function openLocation(file, line) {
    vscode.postMessage({ type: 'openLocation', file, line: Number(line) });
  }

  // LLMs often emit flowchart node labels with a nested location tag —
  // `B[Heading text [src/pages/index.js:133]]` — which mermaid's parser
  // rejects. Quote such labels: `B["Heading text [src/pages/index.js:133]"]`.
  function fixMermaid(source) {
    if (!/^\s*(flowchart|graph)\b/.test(source)) return source;
    return source
      .replace(/([A-Za-z0-9_]+)\[(?!")((?:[^[\]"\n]*\[[^[\]\n]*\])+[^[\]"\n]*)\]/g, '$1["$2"]')
      .replace(/([A-Za-z0-9_]+)\{(?!")([^{}"\n]*\[[^[\]\n]*\][^{}"\n]*)\}/g, '$1{"$2"}')
      .replace(/([A-Za-z0-9_]+)\((?!")([^()"\n]*\[[^[\]\n]*\][^()"\n]*)\)/g, '$1("$2")');
  }

  // Compose the review of one group as GitLab-flavored markdown: TL;DR,
  // behavior changes and the Mermaid diagram (GitLab renders ```mermaid).
  function reviewMarkdown(r) {
    const lines = [`## 🔍 MR Lens review: ${r.group.name}`, ''];
    if (r.tldr) lines.push(`**TL;DR:** ${r.tldr}`, '');
    if (r.summary) lines.push(r.summary, '');
    if (Array.isArray(r.behaviorChanges) && r.behaviorChanges.length) {
      lines.push('**Behavior changes:**');
      for (const c of r.behaviorChanges) lines.push(`- ${c}`);
      lines.push('');
    }
    if (Array.isArray(r.findings) && r.findings.length) {
      lines.push('**Findings:**');
      for (const f of r.findings) {
        const loc = f.file ? ` (\`${f.file}${f.line ? ':' + f.line : ''}\`)` : '';
        lines.push(`- **${f.severity}:** ${f.text}${loc}`);
      }
      lines.push('');
    }
    if (r.mermaid) lines.push('```mermaid', r.mermaid, '```', '');
    lines.push('---', '_Generated by MR Behavior Lens_');
    return lines.join('\n');
  }

  document.addEventListener('click', (e) => {
    const reviewBtn = e.target.closest('button.post-review-btn');
    if (reviewBtn) {
      const r = results[Number(reviewBtn.dataset.idx)];
      if (!r) return;
      reviewBtn.disabled = true;
      vscode.postMessage({
        type: 'postComment',
        id: reviewBtn.id,
        text: reviewMarkdown(r),
        multiline: true,
        label: r.group.name,
      });
      return;
    }
    const btn = e.target.closest('button.comment-btn');
    if (btn) {
      btn.disabled = true;
      vscode.postMessage({
        type: 'postComment',
        id: btn.id,
        text: btn.dataset.text || '',
        file: btn.dataset.file || undefined,
        line: btn.dataset.line ? Number(btn.dataset.line) : undefined,
      });
      return;
    }
    const a = e.target.closest('a.loc');
    if (a) openLocation(a.dataset.file, a.dataset.line);
  });

  let groupCount = 0;
  const results = [];

  function addTldr(idx, result) {
    const text = result.tldr || (result.summary ? result.summary.split(/(?<=[.!?])\s/)[0] : '');
    if (!text) return;
    const section = document.getElementById('tldr');
    const list = document.getElementById('tldr-list');
    const li = document.createElement('li');
    li.innerHTML = `<a class="tldr-group" data-idx="${idx}">${esc(result.group.name)}</a> — ${linkify(text)}`;
    li.querySelector('.tldr-group').addEventListener('click', () => selectTab(idx));
    list.appendChild(li);
    section.hidden = false;
  }

  function selectTab(idx) {
    tabs.querySelectorAll('button').forEach((b, i) => b.classList.toggle('active', i === idx));
    content.querySelectorAll('.group').forEach((g, i) => g.classList.toggle('active', i === idx));
  }

  const STEP_MARKERS = { same: '·', added: '+', removed: '−', changed: '~' };

  function stepsHtml(steps) {
    if (!steps || !steps.length) return '';
    const rows = steps.map((s) => {
      const kind = ['added', 'removed', 'changed'].includes(s.kind) ? s.kind : 'same';
      const loc = s.file
        ? ` <a class="loc" data-file="${esc(s.file)}" data-line="${s.line || 1}">[${esc(s.file)}${s.line ? ':' + s.line : ''}]</a>`
        : '';
      const before = kind === 'changed' && s.before
        ? `<span class="step-before">${linkify(s.before)}</span><span class="step-arrow">→</span> `
        : '';
      return `<li class="step ${kind}"><span class="marker">${STEP_MARKERS[kind]}</span><span class="step-body">${before}${linkify(s.text)}${loc}</span></li>`;
    });
    return `<h3>Behavior flow</h3><ol class="steps">${rows.join('')}</ol>`;
  }

  async function addGroup(result) {
    const idx = groupCount++;
    if (result.mermaid) result.mermaid = fixMermaid(result.mermaid);
    results[idx] = result;
    const btn = document.createElement('button');
    btn.textContent = result.group.name;
    btn.addEventListener('click', () => selectTab(idx));
    tabs.appendChild(btn);
    addTldr(idx, result);

    const div = document.createElement('div');
    div.className = 'group';
    const cacheBadge = result.fromCache ? '<span class="cache-badge">cached · 0 tokens</span>' : '';
    const hasSteps = Array.isArray(result.steps) && result.steps.length > 0;
    const postReview = `<button id="post-review-${idx}" class="post-review-btn" data-idx="${idx}"
      title="Post this group's review (behavior changes + diagram) as a comment on the MR">💬 Post review to MR</button>`;
    div.innerHTML = `
      <h2>${esc(result.group.name)}${cacheBadge}${postReview}</h2>
      ${result.tldr ? `<div class="tldr-line"><strong>TL;DR:</strong> ${linkify(result.tldr)}</div>` : ''}
      <div class="summary">${linkify(result.summary)}</div>
      ${stepsHtml(result.steps)}
      ${result.findings.length ? `<h3>Findings</h3>
      <ul class="findings">${result.findings.map((f, fi) => {
        const loc = f.file ? ` <a class="loc" data-file="${esc(f.file)}" data-line="${f.line || 1}">[${esc(f.file)}${f.line ? ':' + f.line : ''}]</a>` : '';
        const inline = f.file && f.line;
        const comment = ` <button id="comment-${idx}-${fi}" class="comment-btn"
          title="${inline ? 'Post as inline comment on the MR diff' : 'Post as comment on the MR'}"
          data-text="${esc(`**MR Lens ${f.severity}:** ${f.text}`)}"
          ${inline ? `data-file="${esc(f.file)}" data-line="${f.line}"` : ''}>💬</button>`;
        return `<li><span class="sev ${f.severity}">${f.severity}</span> ${linkify(f.text)}${loc}${comment}</li>`;
      }).join('')}</ul>` : ''}
      ${result.behaviorChanges.length ? `<details class="extra-details"${hasSteps ? '' : ' open'}>
      <summary>Behavior changes (${result.behaviorChanges.length})</summary>
      <ul class="changes">${result.behaviorChanges.map((c) => `<li>${linkify(c)}</li>`).join('')}</ul></details>` : ''}
      ${result.mermaid ? `<details class="extra-details"${hasSteps ? '' : ' open'}>
      <summary>Diagram${result.diagramType ? ` · ${esc(result.diagramType)}` : ''}</summary>
      <div class="diagram" id="diagram-${idx}"></div></details>` : ''}
      ${!hasSteps && !result.mermaid ? '<div class="diagram-error">No behavior flow produced for this group.</div>' : ''}`;
    content.appendChild(div);

    if (result.mermaid) {
      const holder = div.querySelector(`#diagram-${idx}`);
      const details = holder && holder.closest('details');
      // Render lazily when the <details> is opened: rendering into a hidden
      // (display:none) container makes mermaid's text measurement return 0/NaN
      // and crash on some diagram types.
      if (details && !details.open) {
        details.addEventListener('toggle', () => {
          if (details.open) renderDiagram(idx, result.mermaid);
        });
      } else {
        renderDiagram(idx, result.mermaid);
      }
    }

    if (idx === 0) selectTab(0);
  }

  async function renderDiagram(idx, source) {
    const holder = document.getElementById(`diagram-${idx}`);
    if (!holder || holder.dataset.rendered) return;
    holder.dataset.rendered = '1';
    try {
      // Validate first — parse gives a clearer error than render on bad input.
      await mermaid.parse(source);
      const { svg } = await mermaid.render(`mmd-${idx}`, source);
      holder.innerHTML = svg;
      // Make [file:line] tags inside the SVG clickable.
      holder.querySelectorAll('text, tspan').forEach((t) => {
        const m = /\[([\w@./\\-]+\.[\w]+):(\d+)\]/.exec(t.textContent || '');
        if (m) {
          t.classList.add('loc-click');
          t.addEventListener('click', () => openLocation(m[1], m[2]));
        }
      });
    } catch (err) {
      // mermaid.render can leave its temp measurement element behind on error.
      const stray = document.getElementById(`dmmd-${idx}`);
      if (stray) stray.remove();
      holder.innerHTML = `<div class="diagram-error">Mermaid render failed:\n${esc(String(err))}\n\n${esc(source)}</div>`;
    }
  }

  window.addEventListener('message', (event) => {
    const msg = event.data;
    if (msg.type === 'commentResult') {
      const btn = msg.id && document.getElementById(msg.id);
      if (btn) {
        btn.disabled = false;
        if (msg.ok) {
          btn.classList.add('posted');
          btn.textContent = btn.id === 'mr-comment' || btn.classList.contains('post-review-btn')
            ? '✓ Posted'
            : '✓';
          btn.title = 'Comment posted';
        }
      }
      return;
    }
    if (msg.type === 'status') {
      status.textContent = msg.message;
      status.classList.remove('error');
    } else if (msg.type === 'group') {
      addGroup(msg.result);
    } else if (msg.type === 'done') {
      if (msg.error) {
        status.textContent = msg.error;
        status.classList.add('error');
      } else {
        status.textContent = groupCount
          ? `Done — ${groupCount} behavior group(s)`
          : 'Done — no behavior groups produced';
      }
    }
  });
})();
